### ISSUE TITLE
add auto update

### ISSUE THREAD

**Issue by amiad** [amiad/IHMGeoJSONWaterholes#1]
* download csv from https://docs.google.com/spreadsheets/d/1BbT762qaYilLnwGD7sJDo8sfs_Y5ExjvixS_Tl3rSas/gviz/tq?tqx=out:csv&sheet=IHM
* convert to GeoJSON - maybe [csv2geojson](http://mapbox.github.io/csv2geojson/)
* commit and push to here

**Comment by zstadler** [comment]
You may look into GitHub Actions

- It can execute the flow on [schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule)
- It can [commit files](https://github.com/marketplace/actions/github-commit-push)

**Comment by amiad** [comment]
I need NodeJS server for the convention to GeoJSON. I have a server but currently without Nodejs.
I'll just use it with systemd timer.

**Comment by amiad** [comment]
In the meantime, I installed it on my computer and scheduled it to run every ten minutes. The computer is on most of the time so it seems to me a sufficient solution.
